GivBack design for Single Project Page
Giveth/giveth-dapps-v2 pull request #1238
Opened 2022-07-28 21:19 UTC by RamRamez

#684

2022-07-29 19:26 UTC, mateodaza requested changes
Awesome work @RamRamez just a little UX detail feedback

2022-07-29 19:26 UTC, mateodaza commented on src/components/views/project/projectDonateCard/GIVbackToast.tsx
> +	const togglePopup = () => setIsPopupOpen(!isPopupOpen);
Can we close the toast when user clicks outside just like all modals currently work? I believe it's better UX

2022-07-30 09:07 UTC, MoeNick commented
@mateodaza this design provided by @Tosinolawale and I thinks its good we fix this toast and don't let the user close it. We wanna emphasize on GIVbacks

2022-07-30 13:00 UTC, mateodaza commented
> @mateodaza this design provided by @Tosinolawale and I thinks its good we fix this toast and don't let the user close it. We wanna emphasize on GIVbacks

<img width="475" alt="image" src="https://user-images.githubusercontent.com/18689480/181915482-1b094f83-51a7-400c-9c62-b13ba6749395.png">

I meant the tooltip :) used the wrong word

2022-08-02 05:26 UTC, MohammadPCh commented
@RamRamez @mateodaza please check the IconWithTooltip component. maybe it helps you.

2022-08-03 23:00 UTC, mateodaza approved these changes
Thanks for your changes!

2022-08-03 23:00 UTC, merged