Discontinued GIVfarm cards
Giveth/giveth-dapps-v2 pull request #1393
Opened 2022-08-18 01:17 UTC by mateodaza

Sets discontinuation for production farms to stop showing on September 8th as it is exactly 3 weeks after August 18th.

Before that date we'll display them by default and tell the user to remove all liquidity from there

@laurenluz  @divine-comedian we can change the date if you disagree

2022-08-18 01:18 UTC, mateodaza commented
100% GIV staking on mainnet
GIV / DAI uniswap on mainnet
GIV/ETH sushiswap on gnosis chain
GIV / xDAI honeyswap on gnosis chain

This is the message
![image](https://user-images.githubusercontent.com/18689480/185184113-9fe86887-43d9-4781-b79e-7c75a61c1dd1.png)

2022-08-18 10:44 UTC, MohammadPCh requested changes
@mateodaza Thanks,
I suggest so  improvements also I have written 2 more suggestions here:

- I think we don't need to add complexity to our app if we want to archive some farms at a specific time, we can easily change them to archived at that time.
- please add configs in development configs too. it helps testers to test it easier.

thanks.

2022-08-18 10:44 UTC, MohammadPCh commented on src/components/homeTabs/GIVfarm.tsx
> +
please move GIVstaking configs to the out of the component, I think the networkProvider.ts is a good place for it.

2022-08-18 10:44 UTC, MohammadPCh commented on src/types/config.ts
> +	active?: boolean;
may we should decide between this and the active property in the simpleStakingConfig,
they are same!

2022-08-18 19:59 UTC, mateodaza commented
As soon as we merge this, I'll create a new PR for manually archiving in Sept 8th

2022-08-19 13:35 UTC, MohammadPCh approved these changes
Thanks @mateodaza

2022-08-19 13:35 UTC, merged