Feature: Edit/removal of project updates
Giveth/giveth-dapps-v2 pull request #141
Opened 2022-03-06 21:45 UTC by mateodaza

2022-03-07 14:29 UTC, RamRamez requested changes
Great! Thanks @mateodaza

2022-03-07 14:29 UTC, RamRamez commented on src/components/views/project/ProjectUpdates.tsx
> +			return gToast(error?.message, {
you can use this function for all toast errors:
`showToastError(err)`

2022-03-07 14:29 UTC, RamRamez commented on src/components/views/project/ProjectUpdates.tsx
>  			return gToast(error?.message, {
you can use this function for all toast errors:
`showToastError(err)`

2022-03-07 23:28 UTC, mateodaza commented on public/images/trash.svg
> +<svg width="14" height="16" viewBox="0 0 14 16" fill="none" xmlns="http://www.w3.org/2000/svg">
we're using it

2022-03-08 13:03 UTC, RamRamez approved these changes

2022-03-08 13:03 UTC, merged