Fixes/ Grammar and semantic issues
Giveth/giveth-dapps-v2 pull request #209
Opened 2022-03-15 04:18 UTC by mateodaza

Merge first #201 and #207

2022-03-15 09:38 UTC, MohammadPCh approved these changes
Thank you for your great job @mateodaza 
I add some change requests that can fix easily.

2022-03-15 09:38 UTC, MohammadPCh commented on src/utils/index.tsx
> +
Please move these hooks to the hooks folder.

2022-03-15 09:38 UTC, MohammadPCh commented on src/components/views/donate/TokenPicker.tsx
> +		</>
Why do you add it to the fragment?

2022-03-15 09:38 UTC, MohammadPCh commented on src/components/views/donate/DonateIndex.tsx
> +		</>
Why do you add fragment?

2022-03-15 09:38 UTC, MohammadPCh commented on src/components/modals/InsufficientFund.tsx
> +	}
you can remove some of them and write like this:
```
	${mediaQueries['desktop']} {
		width: 528px;
	}
```

2022-03-15 09:38 UTC, MohammadPCh commented on src/components/modals/DonateModal.tsx
> +	}
div width is 100% as a default.

2022-03-15 09:38 UTC, MohammadPCh commented on src/components/modals/ChangeNetwork.tsx
> +	}
write like this:
```
width: 100%;
${mediaQueries['tablet']} {
		width: 500px;
	}
```

2022-03-15 09:38 UTC, MohammadPCh commented on src/components/modals/ChangeNetwork.tsx
> +	color: ${brandColors.giv[700]};
Do you consider themes?

2022-03-15 09:39 UTC, MohammadPCh requested changes
Thank you for your great job @mateodaza 
I add some change requests that can fix easily.

2022-03-15 15:31 UTC, mateodaza commented
I believe merge got some grammar issues back to homepage, I'll check again before merging

2022-03-16 15:31 UTC, RamRamez approved these changes

2022-03-16 15:43 UTC, merged