Mt Pelerin integration
Giveth/giveth-dapps-v2 pull request #2321
Opened 2023-03-13 22:32 UTC by mateodaza

Hides onramper for later

2023-03-14 11:05 UTC, MohammadPCh requested changes
@mateodaza Thanks, I added some suggestions.

2023-03-14 11:05 UTC, MohammadPCh commented on src/components/views/purchase/HowToBuyXdai.tsx
> +	];
It's better to move it to the out of the component.

2023-03-14 11:05 UTC, MohammadPCh commented on src/components/views/purchase/PurchaseXDai.tsx
> +					<Right isMobile={isMobile}>
It's better to handle this with media queries.

2023-03-14 11:05 UTC, MohammadPCh commented on src/types/common.ts
> +	type?: string;
please add these to your specific interface, we should keep the base interface abstract.

2023-03-15 22:04 UTC, mateodaza commented on .github/workflows/Build.yml
>              - name: Install dependencies
the onramper widget won't work with v18 😢 
I can leave it like this for the mt pelerin version and worry about this with them later - maybe ask them to upgrade it

2023-03-15 22:04 UTC, mateodaza commented on package.json
> +	},
same reason as above, will fix

2023-03-19 15:08 UTC, MohammadPCh approved these changes
LGTM, Thanks @mateodaza

2023-03-27 21:09 UTC, merged