fix verification button conditions
Giveth/giveth-dapps-v2 pull request #3471
Opened 2023-12-08 20:17 UTC by RamRamez

#3255

2023-12-18 06:23 UTC, aminlatifi requested changes

2023-12-18 06:23 UTC, aminlatifi commented on src/components/views/project/projectActionCard/AdminActions.tsx
>  			label: capitalizeAllWords(
Let's create a variable for each option (e.g. `editProjectOption`, `verifyYourProject` ,...) and at line 102 create the `activeOptoins` by explicitly mentioning active options and not by index
Change this 
	const activeOptions = isActive ? options : [options[0], options[2]];
With this
	const activeOptions = isActive ? options : [editProjectOption, activeDeactiveOption];

2023-12-18 08:08 UTC, aminlatifi requested changes

2023-12-18 08:08 UTC, aminlatifi commented on src/components/views/project/projectActionCard/AdminActions.tsx
>  			label: capitalizeAllWords(
I looked at the `DropDown` component, the `disabled` property has `isHidden` behaviour in fact. Thus, it's better only set the property value per option based on the `isAcive` value. I would suggest even changing the `disabled` property name.

2023-12-28 11:32 UTC, RamRamez commented
@MohammadPCh can you please review this PR? we need to merge it before multisig release.

2023-12-28 11:36 UTC, aminlatifi approved these changes

2023-12-28 12:46 UTC, MohammadPCh approved these changes

2023-12-28 12:46 UTC, merged