Add solana to project filters
Giveth/giveth-dapps-v2 pull request #3481
Opened 2023-12-12 12:14 UTC by alireza-sharifpour

#3472 

The frontend side of the issue is here.
We should wait for Backend.

2023-12-19 11:40 UTC, aminlatifi requested changes

2023-12-19 11:40 UTC, aminlatifi commented on src/components/menu/FilterMenu.tsx
>  ];
```suggestion
if (config.ENABLE_SOLANA) {
    filters.push({
					label: 'Solana',
					value: EProjectsFilter.ACCEPT_FUND_ON_SOLANA,
				},);
}
```

2023-12-19 13:16 UTC, aminlatifi approved these changes

2023-12-20 08:57 UTC, MohammadPCh approved these changes
LGTM, Thanks @alireza-sharifpour

2023-12-20 08:57 UTC, merged