fixed phantom switch wallet issue.
Giveth/giveth-dapps-v2 pull request #3627
Opened 2024-01-15 13:25 UTC by alireza-sharifpour

#3400

2024-01-16 14:57 UTC, aminlatifi requested changes

2024-01-16 14:57 UTC, aminlatifi commented on src/providers/generalWalletProvider.tsx
> +const getSolanaProvider = () => {
```suggestion
const getPhantomSolanaProvider = () => {
```
As its functionality

2024-01-16 14:57 UTC, aminlatifi commented on src/providers/generalWalletProvider.tsx
> +	}
```suggestion
	const provider = (window as any)?.solana;
	if (provider?.isPhantom) {
		return provider;
	}
```

2024-01-17 09:29 UTC, MohammadPCh approved these changes
@alireza-sharifpour Thanks, LGTM

2024-01-17 09:29 UTC, merged