Fix project hydration page
Giveth/giveth-dapps-v2 pull request #586
Opened 2022-04-21 11:32 UTC by MohammadPCh

- #585

2022-04-22 16:54 UTC, RamRamez requested changes

2022-04-22 16:54 UTC, RamRamez commented on pages/project/[projectIdSlug]/index.tsx
> +	return props.project ? (
Have you considered `draft` projects? this way no one can view his/her draft projects anymore.

2022-04-22 16:54 UTC, RamRamez commented on src/components/views/project/ProjectDonateCard.tsx
> +							Learn more
this `learn more` button doesn't exist on figma and I've removed it in PR #592

2022-04-22 19:41 UTC, mateodaza approved these changes

2022-04-22 19:41 UTC, merged

2022-04-23 12:11 UTC, RamRamez commented
@mateodaza What did you merged this PR? Please revert it.

As you see, no one can view his/her draft projects anymore.
![image](https://user-images.githubusercontent.com/73441857/164893883-a3db1c0f-ee0d-44d6-8df2-5e2c3d251908.png)

2022-04-23 12:44 UTC, aminlatifi commented
@MohammadPCh @mateodaza I had to revert it because @RamRamez comments were not addressed

2022-04-23 13:22 UTC, mateodaza commented
@RamRamez @MohammadPCh @aminlatifi wow I totally missed that comment, my bad

2022-04-25 14:48 UTC, MohammadPCh commented
> @MohammadPCh @mateodaza I had to revert it because @RamRamez comments were not addressed

oops!