Price context migration to redux toolkit store
Giveth/giveth-dapps-v2 pull request #790
Opened 2022-05-24 03:05 UTC by mateodaza

2022-05-24 09:01 UTC, MohammadPCh requested changes
@mateodaza 
Thanks for your PR,
I have some suggestions that may help us:
1. remove serializableCheck middleware
2. store bignumbers as string in redux
3. use redux-thunk to create async functions and put them in extraReducer.
4. store 3 states in price slice (give price, eth price, and object of token prices)
5. add 3 extraReducer with thunk that calls an end-point and store data for each state in it.
6. use the price controller to get the real values or if we want to update them.

LMK if I can help :)

2022-05-24 22:36 UTC, mateodaza commented on src/components/controller/price.ctrl.tsx
> +};
This is fetching from the subgraph and not the impact graph, so I'll refactor it to use fetchSubgraph instead

2022-05-24 22:36 UTC, mateodaza commented on src/features/store.ts
> +		}),
Got it, changed ethPrice and givPrice to always be a string

2022-05-24 22:39 UTC, mateodaza commented
@MohammadPCh I added the reducers, not sure why we need the extraReducer as you mention in your comment. 

All other suggestions are solved and ready for review, thank you

2022-05-25 08:50 UTC, MohammadPCh commented
> @MohammadPCh I added the reducers, not sure why we need the extraReducer as you mention in your comment.
> 
> All other suggestions are solved and ready for review, thank you

Thank you @mateodaza, You made a Thunk called getTokenPrice. if you want to use it you have to add an extraReducer for it.

2022-05-30 12:23 UTC, MohammadPCh commented
#824

2022-05-30 12:23 UTC, closed without merging